### PR TITLE
Create .npmignore

### PR DESCRIPTION
**Pull request by tronikos**
Ignore hidden dot files from npm publish

### CODE REVIEW

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
Not stale. Could you please review this to avoid this periodic staleness checks?

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by bwp91** [comment]
These files are already being ignored from publishing to npm

```
.idea
node_modules
*.swp
*.rej
*.orig
```

what else might be published?

**Comment by tronikos** [comment]
The following hidden files/directories in the repo:
```
.github/
.editorconfig
.eslintrc.js
```

For example in my branch compare https://www.npmjs.com/package/homebridge-nest-secure/v/0.0.1?activeTab=code with https://www.npmjs.com/package/homebridge-nest-secure?activeTab=code In the first version where I didn't have the .npmignore these ones were included in the package.

**Comment by tronikos** [comment]
Looking at the beta you recently published you also included these hidden files/directories, see https://www.npmjs.com/package/homebridge-nest/v/4.6.10-beta.0?activeTab=code

**Review by bwp91 — APPROVED** [review]

**Pull request merged**
