### PR TITLE
Remove apiKey and Keep Constant

### PR DESCRIPTION
**Pull request by donavanbecker**

### CODE REVIEW

**Comment by adriancable** [comment]
@donavanbecker - thanks for this - however I am inclined not to accept this PR.

My view is that constants should be constant. The API key is not constant: it changed once in late August 2019 about 3 weeks after Google Accounts were introduced, and there is no reason why it wouldn't change again in the future. Hard-coding it feels like a ticking time bomb - sooner or later things will stop working and it won't be clear to the average user why.

That's why the instructions for Google auth include obtaining the API key and putting it in the config. That way, it doesn't matter if Google changes it.

(Also, Github complains strongly when you try to check in a project which includes what looks like a GCP API key - try it.)

**Comment by donavanbecker** [comment]
@adriancable could we have it as the default on the config.schema.json?

**Comment by donavanbecker** [comment]
@adriancable I have updated the PR so that the API is defaulting the current API, then at least it can be changed easily if needed.

**Comment by adriancable** [comment]
@donavanbecker - what was the base reason for including the API key (as a default or otherwise)? It only adds about 10 seconds of effort when the user goes through the process to get the googleAuth parameters, and because it does change at most infrequently, the user only needs to do this once.

I am just generally very nervous about including Google's internal API keys in a public repo. Google may well object to it. Google may well end up changing it sooner than they otherwise would. I understand the very small convenience advantage, but I just feel in my bones this is a bad idea.

**Comment by donavanbecker** [comment]
Well anyone that has nest-cam plugin being able to get cookie and googleAuth, makes it easier for users since they would get it from the nest cam login.

**Comment by donavanbecker** [comment]
@adriancable would you accept it now? or should I just close this?

**Comment by donavanbecker** [comment]
@adriancable any update? or should I close?

**Comment by adriancable** [comment]
@donavanbecker - leave it open for now if you wish - I've heard from a couple of people that the apiKey is no longer required at all. i.e. just putting XXX in there works. I haven't verified myself yet.

**Comment by donavanbecker** [comment]
@adriancable should I keep this open? or should I close this?

**Comment by adriancable** [comment]
Let’s keep open for now.

**Comment by ihatemyisp** [comment]
@donavanbecker @adriancable 

The API key appears to still be required. Both leaving it blank and putting XXX in do not work. I was able to use the API key from this PR, the non-ft one, and my personal cookie/issueToken and authenticate properly.

**Comment by donavanbecker** [comment]
@adriancable Thoughts on merging this now?

**Comment by ihatemyisp** [comment]
It's been almost a month now and it's still working. In the past, I couldn't get it to stay logged in for more than 2 weeks..ish.

I'll be referencing this elsewhere as necessary.

**Comment by adriancable** [comment]
@donavanbecker - it does appear that the API key is now no longer required in the issue_jwt call. In the latest version of the plug-in (4.5.2), it will still use the API key if provided in the config, but I've updated the instructions to remove the part about getting the API key from the headers, and updated the code to format the headers correctly if no API key is provided. We will hear soon I am sure if my assumption about the API key no longer being needed is wrong! :-)

**Comment by donavanbecker** [comment]
@adriancable Thanks!

**Pull request closed without merging**
