### PR TITLE
For Easy Config with Config-ui-X

### PR DESCRIPTION
**Pull request by donavanbecker**
@adriancable or @chrisjshull Still going to add extra optional parameters. so wait for me to add that before merging. If you prefer not to add this let me know so i don't waste to much time on this ha.

### CODE REVIEW

**Comment by donavanbecker** [comment]
@adriancable I have completed the config. This is what it will look like in [config-ui-x](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI)
Screen Shot 2020-02-05 at 10 49 53 PM

**Comment by donavanbecker** [comment]
@adriancable are you waiting to hap 0.5.x is released?

**Comment by ryanleesmith** [comment]
@chrisjshull @adriancable Are PRs for this repo still being actively monitored?

**Comment by titoudoc** [comment]
I’m wondering the same thing, is https://github.com/adriancable stil here ?

**Comment by adriancable** [comment]
Yep, I’m still here. Sorry if I’m not as responsive as I have in the past … juggling many new commitments.

**Comment by donavanbecker** [comment]
@adriancable can you merge this?

**Comment by donavanbecker** [comment]
Could you merge this so it’s in 4.4.1? @adriancable

**Comment by adriancable** [comment]
@donavanbecker - can do - please can you check it's still fully applicable given that now Nest Account log-ins are only supported via access token due to the recaptcha. Thanks!

**Comment by donavanbecker** [comment]
I will check and let you know! Thanks

**Comment by donavanbecker** [comment]
@adriancable So the email and password for the best account aren’t applicable anymore?

**Comment by adriancable** [comment]
@donavanbecker - no. Nest are now using a recaptcha for email/password access which we can't get around outside a browser.

**Comment by donavanbecker** [comment]
@adriancable So if I just take out email and password we should be good?

**Comment by donavanbecker** [comment]
@adriancable Okay I have take out the email and the password and just left the access token in for the nest account. Let me know if you have any questions. Below is a screenshot of what it looks like.

Screen Shot 2020-02-18 at 7 24 14 PM

**Comment by adriancable** [comment]
@donavanbecker - I think you need to remove the "pin" section, since this isn't relevant any more now that we only support Nest account access via access_token (rather than username and password).

Then I am happy to merge the pull request, once you are happy.

**Comment by donavanbecker** [comment]
Okay will do

**Comment by donavanbecker** [comment]
@adriancable I have removed the pin and attached screenshot of what it looks like. let me know if you would like any other changes done.
Screen Shot 2020-02-20 at 12 51 34 PM

**Comment by donavanbecker** [comment]
@adriancable This is the Nest Account Output Array
```
        {
            "name": "Nest",
            "access_token": "testing",
            "structureId": "testing",
            "fanDurationMinutes": 15,
            "options": [
                "testing",
                "testing"
            ],
            "platform": "Nest"
        }
```

Screen Shot 2020-02-20 at 12 55 07 PM

**Comment by donavanbecker** [comment]
@adriancable This is the Google Account Output Array

```
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "Testing",
                "cookies": "Testing",
                "apiKey": "Testing"
            },
            "structureId": "Testing",
            "fanDurationMinutes": 15,
            "options": [
                "testing",
                "testing"
            ],
            "platform": "Nest"
        }
```

Screen Shot 2020-02-20 at 12 57 05 PM

**Comment by adriancable** [comment]
Looks good to me!

**Pull request merged**
