### PR TITLE
add refresh token authentication

### PR DESCRIPTION
**Pull request by Brandawg93**
Hi!

I'm the author of [homebridge-nest-cam](https://github.com/Brandawg93/homebridge-nest-cam). I've submitted this PR to add refresh token authentication into the nest-connection.js file. This would help bring backward compatibility between both nest and nest-cam plugins.

I intentionally did not modify any documentation or add any custom UI or CLI as I will leave that up to your discretion. Personally, I chose to do both UI and CLI which you are welcome to look at on my repo. If you have any questions or concerns about this commit, just let me know!

### CODE REVIEW

**Comment by fleiscpj** [comment]
Worked as described.  Thanks for coding this!

**Comment by martijnmnnk** [comment]
This makes the plugin so much easier to set up. Big thank you!

**Comment by adriancable** [comment]
Hi @Brandawg93 - this is a very kind contribution! When I get time (hopefully this coming weekend) I'll review fully, and then will merge it in.

**Comment by demonbane** [comment]
@adriancable were you able to get this reviewed? I'm looking forward to having this included in a future release. If you need any volunteers for testing I'm happy to help.

**Comment by adriancable** [comment]
Hi, @demonbane - apologies but 'real life' has got in the way! But rest assured, I absolutely intend to merge this as soon as possible.

**Comment by fleiscpj** [comment]
I've had no problems with connectivity, since I implemented this code
change a month ago.  Thank you!

**Comment by adriancable** [comment]
@Brandawg93 - are you OK with me taking your login.ts (I will convert to JS) from homebridge-nest-cam and adding it to homebridge-nest-cam, to facilitate getting the refresh token?

**Comment by Brandawg93** [comment]
No problem! Just let me know if you have any questions when implementing.

**Comment by demonbane** [comment]
Just checking to make sure that this is still intending to be merged in at some point. Had to do the manual auth thing again today and it reminded me to check in here.

**Comment by adriancable** [comment]
@demonbane - yes! Sorry it's taking longer than I had hoped.

**Comment by cariacou** [comment]
this would be such a good feature. 

I just installed homebridge. nest-cam was so easy to setup. this plugin however is quite confusing.

Since this is in the works, I'll just wait until it's merged to install it

**Comment by samiralam** [comment]
Bumping to keep this open 😄

**Comment by adriancable** [comment]
Thanks for your patience, all! Will aim to have this ready to go by the end of the day.

**Comment by adriancable** [comment]
@fleiscpj + @martijnmnnk + @demonbane + @samiralam + @cariacou - the refresh token authentication method is now checked in to github. Can you kindly follow the instructions in the README to get it set up, and let me know how you get on. Want some extra eyes on the instructions to 'debug' before publishing to npm. Thank you!

**Comment by demonbane** [comment]
I'm happy to test, I just need some instructions on how to install the version from the repo in place of/alongside the npm version I already have installed.

**Comment by adriancable** [comment]
@demonbane - you should be able to do something like:

npm install https://github.com/chrisjshull/homebridge-nest

This will overwrite the npm version with the latest version on GitHub.

**Comment by demonbane** [comment]
I didn't get a chance to test this before the full release went out but just wanted to let you know that it definitely does work. Just switched over from cookie to refreshtoken and it worked like a charm. Thanks again!

**Pull request merged**
