### PR TITLE
Auth via Access Token in addition to Username + Password

### PR DESCRIPTION
**Pull request by ablyler**

### CODE REVIEW

**Comment by adriancable** [comment]
Hi @ablyler - first thanks for spotting the typo (in objectList set-up) which would prevent the 2FA mode from working correctly. That's fixed in the latest commit!

Regarding access token support, I did consider this previously but it has a bad consequence that I was afraid would trip people up, so I decided against including it. The problem with using an access token obtained via curl is that access tokens expire. If you are running homebridge-nest for a long period of time (as most people do), once the access token expires the plug-in will no longer be able to communicate with Nest and your HomeKit devices will become unresponsive. Right now homebridge-nest deals with that by re-authenticating with username/password to get a new access token if the old one expires, so your service is uninterrupted. But, this is not possible if all that's provided to the plug-in is a single access token.

Feel free to try and convince me otherwise though, I am all ears.

**Comment by ablyler** [comment]
Hi @adriancable, thanks for creating this project!

I totally understand the concern about having the access token expire. However, in my experience these tokens are long lived. I am using the same concept with my usage of the https://github.com/KhaosT/homebridge-nest-cam project, and it has been working for months without me changing the access token.

For me, moving to the access token allows me to have my homebridge setup in a docker and have auto updates setup. Since I have 2FA, using the username + password + 2FA prevents me from being able to have auto updates setup.

Maybe we could set it up to allow both authentication methods? Are you open to that idea?

Thanks again!

**Comment by ablyler** [comment]
@adriancable if you are open to it, I can modify this PR to allow for users to either user username + password or access token. I think that might be the best option, give the two separate use cases. What are your thoughts?

**Comment by adriancable** [comment]
Andy - I'm open to that.

**Comment by ablyler** [comment]
@adriancable take a look, I've updated the PR.

**Comment by adriancable** [comment]
Thanks @ablyler - I am planning to release 3.2.4 shortly (which won't have this) then will merge your commit so it'll go into 3.2.5.

**Comment by adriancable** [comment]
Now added to 3.3.0. Thank you!

**Pull request closed without merging**
