### PR TITLE
Remove unused login.js and readline dependency to save on 1.9 MB

### PR DESCRIPTION
**Pull request by tronikos**
- login.js doesn't work anymore
- the reference to it was removed from the README in https://github.com/chrisjshull/homebridge-nest/commit/999faba0407c4560c31f6c1e04756138c596daa9
- readline dependency only used in the login.js pulls large tests

### CODE REVIEW

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
not stale

**Review by ameyakoshti — APPROVED** [review]

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
@bwp91 as a new maintainer of this repo could you review this?

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Pull request closed without merging**
