### PR TITLE
Single mode support

### LINKED ISSUE #6: can't cool but show cool option in homekit
Hi, i have installed the forked version of chrisjshull, my heating system is boiler type, can't cool, but in homekit it show cool options and in eco mode show the heat/cool temperature. Is there a way to remove the cool controls if not supported by system? Thankyou.

### PR DESCRIPTION
**Pull request by chrisjshull**
fixes #6 

to test: `npm install -g "git://github.com/chrisjshull/homebridge-nest.git#single-mode"`

### CODE REVIEW

**Comment by chrisjshull** [comment]
@dvd2000k, can you confirm the fix. then I'll merge to master

**Comment by dvd2000k** [comment]
In home app now it show only heating or off (correct)
In eve or others homekit app it show again cooling mode. (and target cooling temperature)
If i put nest in eco mode in all homekit app it show cooling/heating range.

**Comment by chrisjshull** [comment]
interesting. can you:

1. quit homebridge
1. turn on eco mode
1. launch homebridge in debug mode `DEBUG=* homebridge -D`
1. attach the log once homebridge is up and running.

**Comment by dvd2000k** [comment]
here is the log part for nest:

[2018-02-14 23:05:43] [Nest] initing thermostat "Family Room Thermostat": deviceId: xjkv4OPLoWPf-9bE5ArUu96P5xNEVa7p structureId: 9kTkCP1Wip_Tlfsaj7aIqwQdoDNVhpeIQbjdWtllaEMixElkgOHmtg
[2018-02-14 23:05:43] [Nest] { ambient_temperature_c: 19.5,
  ambient_temperature_f: 68,
  away_temperature_high_c: 24,
  away_temperature_high_f: 76,
  away_temperature_low_c: 14,
  away_temperature_low_f: 58,
  can_cool: false,
  can_heat: true,
  device_id: 'xjkv4OPLoWPf-9bE5ArUu96P5xNEVa7p',
  eco_temperature_high_c: 24,
  eco_temperature_high_f: 76,
  eco_temperature_low_c: 14,
  eco_temperature_low_f: 58,
  fan_timer_active: false,
  fan_timer_duration: 15,
  fan_timer_timeout: '1970-01-01T00:00:00.000Z',
  has_fan: false,
  has_leaf: true,
  humidity: 40,
  hvac_mode: 'eco',
  hvac_state: 'off',
  is_locked: false,
  is_online: true,
  is_using_emergency_heat: false,
  label: '',
  last_connection: '2018-02-14T22:03:12.001Z',
  locale: 'it-IT',
  locked_temp_max_c: 22,
  locked_temp_max_f: 72,
  locked_temp_min_c: 20,
  locked_temp_min_f: 68,
  name: 'Family Room',
  name_long: 'Family Room Thermostat',
  previous_hvac_mode: 'heat',
  software_version: '5.6.6-4',
  structure_id: '9kTkCP1Wip_Tlfsaj7aIqwQdoDNVhpeIQbjdWtllaEMixElkgOHmtg',
  sunlight_correction_active: false,
  sunlight_correction_enabled: true,
  target_temperature_c: 19,
  target_temperature_f: 67,
  target_temperature_high_c: 24,
  target_temperature_high_f: 75,
  target_temperature_low_c: 20,
  target_temperature_low_f: 68,
  temperature_scale: 'C',
  time_to_target: '~0',
  time_to_target_training: 'ready',
  where_id: 'DEejeuqsg4C4JBKJOpHB0GFJ7QLBBAouaip5937jsRZv8ApzdjSYoA',
  where_name: 'Family Room' }
[2018-02-14 23:05:43] [Nest] Current temperature for Family Room Thermostat is: 19.5 °C and 67.1 °F
[2018-02-14 23:05:43] [Nest] Current humidity for Family Room Thermostat is: 40%
[2018-02-14 23:05:43] [Nest] getTargetTemperature 19
[2018-02-14 23:05:43] [Nest] Target heating/cooling state for Family Room Thermostat is: Auto
[2018-02-14 23:05:43] [Nest] Cooling threshold temperature for Family Room Thermostat is: 24 °C and 75.2 °F
[2018-02-14 23:05:43] [Nest] Heating threshold temperature for Family Room Thermostat is: 14 °C and 57.2 °F
[2018-02-14 23:05:43] [Nest] Home Occupied for Family Room Thermostat is: true
[2018-02-14 23:05:43] [Nest] Eco Mode for Family Room Thermostat is: true
[2018-02-14 23:05:43] [Nest] Eco Mode for Family Room Thermostat is: true
[2018-02-14 23:05:43] [Nest] Has Leaf for Family Room Thermostat is: true
[2018-02-14 23:05:43] [Nest] Sunlight Correction Enabled for Family Room Thermostat is: true
[2018-02-14 23:05:43] [Nest] initing protect "Family Room Nest Protect": deviceId: Yeeh98M4-bLkdBSH5fU2Wt6P5xNEVa7p structureId: 9kTkCP1Wip_Tlfsaj7aIqwQdoDNVhpeIQbjdWtllaEMixElkgOHmtg
[2018-02-14 23:05:43] [Nest] { battery_health: 'ok',
  co_alarm_state: 'ok',
  device_id: 'Yeeh98M4-bLkdBSH5fU2Wt6P5xNEVa7p',
  is_manual_test_active: false,
  is_online: true,
  last_connection: '2018-02-14T13:15:26.813Z',
  last_manual_test_time: '2017-02-26T14:08:14.000Z',
  locale: 'it-IT',
  name: 'Family Room',
  name_long: 'Family Room Nest Protect',
  smoke_alarm_state: 'ok',
  software_version: '3.1.4rc3',
  structure_id: '9kTkCP1Wip_Tlfsaj7aIqwQdoDNVhpeIQbjdWtllaEMixElkgOHmtg',
  ui_color_state: 'green',
  where_id: 'DEejeuqsg4C4JBKJOpHB0GFJ7QLBBAouaip5937jsRZv8ApzdjSYoA',
  where_name: 'Family Room' }
[2018-02-14 23:05:43] [Nest] Online status (Smoke) for Family Room Nest Protect is: online
[2018-02-14 23:05:43] [Nest] Online status (CO) for Family Room Nest Protect is: online
[2018-02-14 23:05:43] [Nest] Initializing platform accessory 'Family Room Thermostat'...
[2018-02-14 23:05:43] [Nest] Initializing platform accessory 'Family Room Nest Protect'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

**Comment by chrisjshull** [comment]
Thanks @dvd2000k, can you give it a try now?

**Comment by dvd2000k** [comment]
Thankyou! Now in apple home app is working perfectly! 

But i don't know why in eve and Matthias home app still show the cool mode and the target cool temperature control.

**Comment by chrisjshull** [comment]
I suspect they’ve either cached the old info, or they assumed all thermostats have both capabilities.

**Pull request merged**
