### PR TITLE
Remove useless warnings section

### PR DESCRIPTION
**Pull request by tronikos**
I'm planning to keep my own homebridge-nest-secure fork and set up my own package. I'd like to auto sync changes from your repository and I'm trying to avoid conflicts at line 48 that this PR removes.

### CODE REVIEW

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Comment by tronikos** [comment]
Not stale

**Review by bwp91 — APPROVED** [review]

**Pull request merged**
