### PR TITLE
Add info about running login.js in new computer

### PR DESCRIPTION
**Pull request by jlian**
I tried just doing `node login.js` on my Mac and it didn't work because I had to run `npm install` first. Making this clear for others as well.

### CODE REVIEW

**Comment by adriancable** [comment]
Hi @jlian - thanks for this PR but I'm a little confused!

If you installed the plug-in using npm, then 'npm install' is run automatically and so shouldn't be needed before node login.js.

If you installed the plug-in 'manually' by cloning the Github repo, then yes you would need to run 'npm install' but that's true just to operate the plug-in, and isn't specific to being able to run login.js. So even then, no extra step is required just to run login.js.

Can you help me understand where the disconnect may be? Thank you!

**Comment by jlian** [comment]
In my case, my homebridge is running on a raspberry pi, it uses the official homebridge and it's headless - no browser access. Since your `login.js` script requires browser access I had to pull out my Mac to run it, which doesn't run homebridge at all so it doesn't have any of the plug-ins installed. Does that make sense?

I suppose we could shorten it with `npm install https://github.com/chrisjshull/homebridge-nest`, I can make a quick update

**Comment by adriancable** [comment]
@jlian - you need a browser to complete the login process, but the browser doesn't need to be running on the same device as Homebridge. You have a headless Raspberry Pi running Homebridge which is pretty common - but why do you need to 'move' login.js to your Mac? Yes if you do that, you will then need to fix up the dependencies. But unless I am misunderstanding, it feels like your PR is solving a problem that doesn't need to exist. You shouldn't be 'moving' login.js anywhere. You should run it wherever Homebridge is running.

If you run Homebridge on the headless Raspberry Pi, then you should also run node login.js on the headless Raspberry Pi. All the dependencies will by definition be in place and so you don't need to do 'npm install'. Yes you need to copy a URL into a browser but you can do that on whatever device you are using to SSH into the Pi (your Mac, presumably).

I'll leave this open in case I really have misunderstood something about what you're trying to achieve ...

**Comment by jlian** [comment]
That makes sense actually, not sure why I got the idea to have to use a mac for this. Thanks!

**Pull request closed without merging**
